<<<<<<< HEAD
||||||| MERGE BASE
=======
import io
import json
import re
import urllib.parse

from odoo.addons.web.controllers import report
from odoo.http import request, route
from PyPDF2 import PdfFileReader


class ReportController(report.ReportController):
    def _count_pages_with_products(self, pdf_reader, picking_id):
        """
        Cuenta las páginas que realmente contienen productos
        analizando el contenido de texto de cada página.
        Usa identificadores de producto (código interno, código de barras)
        para la detección, de forma independiente del idioma.
        """
        picking = request.env["stock.picking"].browse(picking_id)
        move_lines = picking.move_line_ids

        # Si no hay move_lines, usar move_ids como fallback
        if not move_lines:
            move_lines = picking.move_ids

        # Recopilar identificadores de producto
        product_identifiers = set()
        for line in move_lines:
            product = getattr(line, "product_id", None)
            if product:
                if product.default_code:
                    product_identifiers.add(product.default_code.lower().strip())
                if product.barcode:
                    product_identifiers.add(product.barcode.lower().strip())

        pages_with_products = 0

        for page_num in range(len(pdf_reader.pages)):
            try:
                page = pdf_reader.pages[page_num]
                text = page.extract_text()
                if not text:
                    continue
                text_lower = text.lower()
                if product_identifiers and any(pid in text_lower for pid in product_identifiers):
                    has_products = True
                else:
                    # Fallback: patrón numérico genérico (independiente del idioma)
                    has_products = bool(re.search(r"\b\d+[.,]\d+\b", text_lower))

                if has_products:
                    pages_with_products += 1

            except Exception:
                # Si hay error extrayendo texto, asumimos que tiene productos
                pages_with_products += 1

        # Asegurar que al menos hay 1 página con productos
        return max(1, pages_with_products)

    @route()
    def report_download(self, data, context=None, token=None, **kwargs):
        """This function is used by 'qwebactionmanager.js' in order to trigger
        the download of a py3o/controller report.
        :param data: a javascript array JSON.stringified containg report
        internal url ([0]) and type [1]
        :returns: Response with a filetoken cookie and an attachment header
        """
        response = super().report_download(data, context=context, token=token, **kwargs)
        # NTH detect if the binary is a PDF, no matter ifn it was generated by a QWeb or Aeroo
        requestcontent = json.loads(data)
        url, type = requestcontent[0], requestcontent[1]
        if type == "aeroo" and "remito" in url:
            context_part = json.loads(data)[0].split("context=")[1]
            context_dict = json.loads(urllib.parse.unquote(context_part))
            picking_id = context_dict.get("active_ids")
            assign = context_dict.get("assign")
            book_id = request.env["stock.picking"].browse(picking_id).book_id
            if assign and book_id and picking_id:
                # Copias del reporte que se imprime, resuelto por su report_name en la URL.
                copies = request.env["ir.actions.report"]._get_voucher_copies_from_url(url)
                # Check if response is PDF, if not (like .doc), assign 1 voucher
                try:
                    pdf_response = response.response[0]
                    reader = PdfFileReader(io.BytesIO(pdf_response))

                    # Usar el nuevo método para contar páginas con productos
                    if copies:
                        total_pages = int(len(reader.pages) / copies)
                        number_pages = self._count_pages_with_products(reader, picking_id)
                        # Ajustar por número de copias
                        number_pages = min(number_pages, total_pages)
                    else:
                        number_pages = self._count_pages_with_products(reader, picking_id)
                except Exception:
                    # If not PDF or can't process (like .doc), assign only 1 voucher
                    number_pages = 1

                # See if there are vouchers already assigned. If not, assign them
                # based on the real page count, then re-render so the numbers show.
                picking = request.env["stock.picking"].browse(picking_id)
                if not picking.voucher_ids and book_id:
                    picking.assign_numbers(number_pages, book_id)
                    picking.env.flush_all()
                    # Re-render: the first PDF had no numbers yet; this second
                    # render includes the just-assigned voucher numbers.
                    try:
                        response = super().report_download(data, context=context, token=token, **kwargs)
                    except Exception:
                        pass

        elif "report_deliveryslip" in url:
            # Fallback: if numbers weren't pre-assigned (e.g. printed outside
            # do_print_and_assign), assign them post-render based on actual page count.
            # Note: in this path the first PDF won't show the numbers; use
            # do_print_and_assign to guarantee numbers on the first print.
            match = re.search(r"(\d+)$", json.loads(data)[0])
            if match:
                picking_id = int(match.group(1))
                picking = request.env["stock.picking"].browse(picking_id)
                book_id = picking.book_id
                if book_id and book_id.autoprinted == False and picking_id:
                    if not picking.voucher_ids and book_id:
                        try:
                            pdf_response = response.response[0]
                            reader = PdfFileReader(io.BytesIO(pdf_response))

                            copies_result = request.env["ir.actions.report"].search_read(
                                [("report_name", "=", "stock.report_deliveryslip")], ["l10n_ar_copies"], limit=1
                            )
                            copies = copies_result[0]["l10n_ar_copies"] if copies_result else None

                            if copies == "triplicado":
                                total_pages = int(len(reader.pages) / 3)
                            elif copies == "duplicado":
                                total_pages = int(len(reader.pages) / 2)
                            else:
                                total_pages = len(reader.pages)

                            number_pages = self._count_pages_with_products(reader, picking_id)
                            number_pages = min(number_pages, total_pages)
                        except Exception:
                            number_pages = 1

                        picking.assign_numbers(number_pages, book_id)
                        picking.env.flush_all()
                        # Re-render so the assigned numbers appear on the first PDF.
                        try:
                            response = super().report_download(data, context=context, token=token, **kwargs)
                        except Exception:
                            pass

                elif book_id and picking_id:
                    if not picking.voucher_ids and book_id:
                        picking.assign_numbers(1, book_id)

        return response

>>>>>>> FORWARD PORTED
