{
    "name": "Barcode Multi Barcode",
    "version": "18.0.1.0.0",
    "category": "Warehouse Management",
    "sequence": 14,
    "summary": "",
    "author": "ADHOC SA",
    "website": "www.adhoc.com.ar",
    "license": "AGPL-3",
    "images": [],
    "depends": [
        "stock_barcode",
        "product_multi_barcode",
    ],
    "data": [],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "application": False,
}
