from odoo import fields, models
from odoo.osv import expression


class StockWarehouseOrderpoint(models.Model):
    """Defines Minimum stock rules."""

    _inherit = "stock.warehouse.orderpoint"

    """ add store = True for recompute fields from wizard. Only recompute by wizard """
    rotation_stdev = fields.Float(store=True)

    warehouse_rotation_stdev = fields.Float(store=True)

    rotation = fields.Float(store=True)

    warehouse_rotation = fields.Float(store=True)

    qty_forecast_stored = fields.Float(
        string="Previsión",
    )

    def update_qty_forecast(self):
        for rec in self:
            rec.qty_forecast_stored = rec.qty_forecast

    def _get_orderpoint_products(self):
        """Always use standard behavior to ensure temporary orderpoints are created.

        Filtering is handled at the view level, not at creation level, to ensure
        all necessary temporary orderpoints are generated by Odoo's standard logic.
        """
        return super()._get_orderpoint_products()

    def _get_orderpoint_locations(self):
        """Always use standard behavior to ensure temporary orderpoints are created.

        Filtering is handled at the view level, not at creation level.
        """
        return super()._get_orderpoint_locations()

    def action_replenish(self):
        """Override to optionally apply filters from wizard context.

        Only applies filters when they are explicitly set in context (coming from wizard).
        This preserves standard Odoo behavior for automatic temporary orderpoint creation.
        """
        super().action_replenish()
        action = self.with_context()._get_orderpoint_action()

        # Only apply additional domain filters if coming from wizard with filters
        has_filters = any(
            [
                self._context.get("filter_products"),
                self._context.get("filter_categories"),
                self._context.get("filter_suppliers"),
                self._context.get("filter_locations"),
            ]
        )

        if has_filters:
            orderpoint_domain = self.with_context().env["stock.warehouse.orderpoint.wizard"].get_orderpoint_domain()
            action["domain"] = expression.AND(
                [
                    action.get("domain", "[]"),
                    orderpoint_domain,
                ]
            )
        return action

    def update_qty_to_order_orderpoint(self):
        # Esto lo hacemos ya que el metodo es privado y no podemos llamarlo luego en el .js
        valid_orderpoints = self.exists()
        if valid_orderpoints:
            valid_orderpoints._compute_qty_to_order()
