{
    "name": "Stock currency valuation",
    "version": "18.0.1.1.0",
    "category": "Warehouse Management",
    "sequence": 14,
    "summary": "",
    "author": "ADHOC SA",
    "website": "www.adhoc.com.ar",
    "images": [],
    "depends": [
        "stock_account",
        "stock_landed_costs",
        "product_replenishment_cost",
    ],
    "data": [
        "views/product_category.xml",
        "views/stock_picking.xml",
        "views/stock_landed_cost_views.xml",
        "views/product.xml",
        "views/stock_valuation_layer.xml",
        "wizard/stock_valuation_layer_revaluation_views.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
    "assets": {},
    "license": "AGPL-3",
}
