{
    "name": "Stock currency valuation",
    "version": "19.0.1.0.0",
    "category": "Warehouse Management",
    "sequence": 14,
    "summary": "",
    "author": "ADHOC SA",
    "website": "www.adhoc.com.ar",
    "images": [],
    "depends": [
        "stock_account",
        "stock_account_ux",
        "stock_landed_costs",
        "product_replenishment_cost",
    ],
    "data": [
        "views/product_category.xml",
        "views/stock_picking.xml",
        "views/stock_quant_views.xml",
        "report/stock_avco_audit_report_views.xml",
        "views/stock_landed_cost_views.xml",
        "views/product.xml",
        "views/stock_move_views.xml",
        "views/product_value_views.xml",
        "views/stock_move_valuation_views.xml",
    ],
    "demo": [
        "demo/stock_currency_valuation_demo.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
    "assets": {},
    "license": "AGPL-3",
}
